# Generated by Django 6.0.6 on 2026-08-11 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_author_bio_alter_author_birth_date_and_more'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='deliverydata',
            name='city',
            field=models.CharField(max_length=150, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='deliverydata',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='deliverydata',
            name='post_service',
            field=models.CharField(max_length=200, verbose_name='Post Service'),
        ),
        migrations.AlterField(
            model_name='deliverydata',
            name='post_service_branch',
            field=models.CharField(max_length=200, verbose_name='Post Service Branch'),
        ),
        migrations.AlterField(
            model_name='deliverydata',
            name='street',
            field=models.CharField(max_length=150, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='lastvieweddata',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.book', verbose_name='Book'),
        ),
        migrations.AlterField(
            model_name='lastvieweddata',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
    ]
