# Generated by Django 6.0.6 on 2026-06-25 10:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='category',
            name='bio',
            field=models.TextField(default='No bio yet'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='bio',
            field=models.TextField(default='No bio yet'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='bio',
            field=models.TextField(default='No bio yet'),
        ),
    ]
