# Generated by Django 6.0.6 on 2026-06-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_autor_birth_date_category_bio_alter_autor_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='calculated_rating',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
