# Generated by Django 6.0.6 on 2026-07-12 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'permissions': [('view_avg_price', 'Can view average price per category')]},
        ),
    ]
