# Generated by Django 6.0.6 on 2026-07-12 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('can_manage_all_orders', 'Може переглядати й змінювати всі замовлення'), ('can_view_reports', 'Може переглядати звіти/статистику')]},
        ),
    ]
